### ISSUE TITLE
User Profile Page

### ISSUE THREAD

**Issue by robpedersendev** [Growers-Brains-App/Front-End#13]
This is the page where users can post their plant pictures and details, share their planting tips and other stuff that will be helpful to other users

Figma wireframe - https://www.figma.com/file/gUdZcQKYryEyy70LMHuJTI/Growers-Brains-MVP?node-id=0%3A88

--MVP requirements--
- Name
- Date joined
- Profile picture
- All Images ever uploaded Including -image uploaded for disease scanning and others
- A short Bio them

**Comment by robpedersendev** [comment]
- [ ] Assign task to yourself

**Comment by harshlele** [comment]
https://github.com/Growers-Brains-App/Front-End/tree/profile_page ok so i have moved that branch here, (will make a PR after I add a few more features and when I'm sure it works correctly)
